jobs:
  - job: ${{ parameters.name }}
    displayName: CI build for ${{ parameters.displayName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    dependsOn:
      - BuildAndTestsOnWindows
      - BuildAndTestsOnUnix

    steps:
      - checkout: self
        clean: true
        lfs: true

      - task: UseDotNet@2
        displayName: Use .NET Core SDK ${{ parameters.dotNetCoreVersion3 }}
        inputs:
          version: ${{ parameters.dotNetCoreVersion3 }}

      - task: UseDotNet@2
        displayName: Use .NET Core SDK ${{ parameters.dotNetCoreVersion2 }}
        inputs:
          version: ${{ parameters.dotNetCoreVersion2 }}

      - powershell: docker ps -a -q | % { docker rm $_ --force }
        displayName: Remove All Orphaned Containers

      - powershell: |
          $env:SONARCLOUD_TOKEN = "$(sonarcloud.token)"
          ./build.sh --target=Sonar
        displayName: Sonar

      - powershell: |
          $env:FEED_APIKEY = "$(feed.apikey)"
          ./build.sh --target=Publish
        displayName: Publish
