jobs:
  - job: ${{ parameters.name }}
    displayName: CI build for ${{ parameters.name }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    dependsOn:
      - Windows
      - Linux

    steps:
      - task: UseDotNet@2
        displayName: Use .NET Core SDK ${{ parameters.dotNetCoreVersion }}
        inputs:
          version: ${{ parameters.dotNetCoreVersion }}

      - powershell: ./tools/dotnet-cake --target=Sonar
        displayName: Sonar
        env:
          SONARQUBE_TOKEN: $(sonarcloud.token)

      - powershell: ./tools/dotnet-cake --target=Publish
        displayName: Publish
        env:
          NUGET_APIKEY: $(feed.apikey)
