name: $(date:yyyyMMdd)$(rev:.r)

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  dotNetCoreVersion: 2.2.401
  cakeVersion: 0.35.0

trigger:
  - master
  - develop
  - bugfix/*
  - feature/*

pr:
  - master
  - develop

jobs:
  # Run Windows build and tests.
  - template: template/build.yml
    parameters:
      name: Windows
      vmImage: windows-2019
      dotNetCoreVersion: $(dotNetCoreVersion)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Windows

  # Run Linux build and tests.
  - template: template/build.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04
      dotNetCoreVersion: $(dotNetCoreVersion)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers

  # Run static code analysis and publish artifact.
  # Until now, we do not cover Windows only tests.
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop') }}:
    - template: template/publish.yml
      parameters:
        name: Linux
        vmImage: ubuntu-16.04
        dotNetCoreVersion: $(dotNetCoreVersion)
        cakeVersion: $(cakeVersion)
