version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "monthly"
    ignored_updates:
      - match:
          dependency_name: "*"
    default_reviewers:
      - "HofmeisterAn"
    default_assignees:
      - "HofmeisterAn"
